config/routes.rb
FirstApp::Application.routes.draw do

  get "users/home"
  get "users/about"

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
 validates :name, presence: true, length: { maximum: 50 }
 VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
 validates :email, presence:   true,
                   format:     { with: VALID_EMAIL_REGEX },
                   uniqueness: { case_sensitive: false }
 #has_secure_password
 validates :password, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def home


  end

  def about
    user = @user = User.new
    user.name = params[:name]
    user.email = params[:email]
    user.password = params[:password]

    user.save
    

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FirstApp</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/about.html.erb
<%= render 'shared/error_messages' %>
<%= @user.name %>
<%= @user.email %>
<%= @user.password %>
<%= @user.id %>

app/views/users/home.html.erb
<h1>hello</h1>

<%= form_tag('/users/about', {:method => 'get'}) { %>

  <%= text_field_tag(:name, params[:name]) %>
  <%= text_field_tag(:email, params[:email]) %>
  <%= text_field_tag(:password, params[:password]) %>


<%= submit_tag(users_about_path, :class => 'btn') %>


<% } %>